# sqlファイルで日本語を使うための設定
spring.datasource.sqlScriptEncoding: UTF-8

# 組み込みインメモリDBを使う設定
spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/tmp/testdb
    username: sa
    password: